spring.application.name=Security
spring.port =3000

logging.level.root = info


spring.datasource.url= jdbc:mysql://localhost:3306/SECURITY_DATABASE?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql: true
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.orm.jdbc.bind: TRACE

#spring.security.user.name=prabhuteja
#spring.security.user.password=$2a$10$KA2bRvbwVgG3yVUByT2Uy.xpS6z2G4eWhIBrqi.0jaNkRsm4rjdVm

spring.jpa.open-in-view=false

security.jwt.secret=CKkodf9QxjPQQkWvpvTdE+cpNeyiy/jgA9sapYXMpRt1lqmRpabuB5ggz8pZbpySYdEAJtQ0U1igpp2D6enDvw==
security..jwt.issuer=auth-service-dev
security.jwt.access-expiration = 900000
security.jwt.refresh-expiration = 604800000
